### ISSUE TITLE
Mac install Error

### ISSUE THREAD

**Issue by lizhongit** [go-delve/homebrew-delve#3]
``` bash
localhost:~ Lee$ brew install go-delve/delve/delve
==> Installing delve from go-delve/homebrew-delve
==> Downloading https://github.com/derekparker/delve/archive/v0.11.0-alpha.tar.gz
Already downloaded: /Library/Caches/Homebrew/delve-0.11.0.tar.gz
==> dlv-cert is already installed, no need to create it
==> make build BUILD_SHA=v0.11.0
Last 15 lines from /Users/lee/Library/Logs/Homebrew/delve/01.make:
    /usr/local/Cellar/go/1.5.1/libexec/src/github.com/spf13/cobra (from $GOROOT)
    /private/tmp/delve20160918-5331-1ukjof1/delve-0.11.0-alpha/src/github.com/spf13/cobra (from $GOPATH)
src/github.com/derekparker/delve/dwarf/reader/reader.go:6:2: cannot find package "golang.org/x/debug/dwarf" in any of:
    /usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/debug/dwarf (from $GOROOT)
    /private/tmp/delve20160918-5331-1ukjof1/delve-0.11.0-alpha/src/golang.org/x/debug/dwarf (from $GOPATH)
src/github.com/derekparker/delve/proc/proc_darwin.go:12:2: cannot find package "golang.org/x/debug/macho" in any of:
    /usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/debug/macho (from $GOROOT)
    /private/tmp/delve20160918-5331-1ukjof1/delve-0.11.0-alpha/src/golang.org/x/debug/macho (from $GOPATH)
src/github.com/derekparker/delve/proc/proc_darwin.go:21:2: cannot find package "golang.org/x/sys/unix" in any of:
    /usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/sys/unix (from $GOROOT)
    /private/tmp/delve20160918-5331-1ukjof1/delve-0.11.0-alpha/src/golang.org/x/sys/unix (from $GOPATH)
src/github.com/derekparker/delve/config/config.go:10:2: cannot find package "gopkg.in/yaml.v2" in any of:
    /usr/local/Cellar/go/1.5.1/libexec/src/gopkg.in/yaml.v2 (from $GOROOT)
    /private/tmp/delve20160918-5331-1ukjof1/delve-0.11.0-alpha/src/gopkg.in/yaml.v2 (from $GOPATH)
make: *** [build] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/go-delve/homebrew-delve/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
    from /usr/local/Library/Homebrew/utils.rb:472:in `open'
    from /usr/local/Library/Homebrew/utils.rb:502:in `issues_matching'
    from /usr/local/Library/Homebrew/utils.rb:534:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
    from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
    from /usr/local/Library/Homebrew/exceptions.rb:261:in `dump'
    from /usr/local/Library/brew.rb:195:in `rescue in <main>'
    from /usr/local/Library/brew.rb:79:in `<main>'

```

Who can tell me how to fix the issue, Thanks!

**Comment by aarzilli** [comment]
I think you need at least go 1.6 to use the brew recipe, with go 1.5 you will need to set GOVENDOREXPERIMENT but I don't know how to do that through brew.

**Comment by LalatenduMohanty** [comment]
I am using go version 1.6.2 but still faced the issue on OS X
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:436:in `open'
	from /usr/local/Library/Homebrew/utils.rb:466:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:498:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:160:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'
```

**Comment by aarzilli** [comment]
@LalatenduMohanty is that the full error message?
cc @steeve

**Comment by LalatenduMohanty** [comment]
@aarzilli  Here is the full error

```
$ brew install go-delve/delve/delve
==> Installing delve from go-delve/homebrew-delve
==> Downloading https://github.com/derekparker/delve/archive/v0.11.0-alpha.tar.gz
Already downloaded: /Library/Caches/Homebrew/delve-0.11.0.tar.gz
==> dlv-cert is already installed, no need to create it
==> make build BUILD_SHA=v0.11.0
Last 15 lines from /Users/lmohanty/Library/Logs/Homebrew/delve/01.make:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/spf13/cobra (from $GOROOT)
	/private/tmp/delve20161005-6837-6240x5/delve-0.11.0-alpha/src/github.com/spf13/cobra (from $GOPATH)
src/github.com/derekparker/delve/dwarf/reader/reader.go:6:2: cannot find package "golang.org/x/debug/dwarf" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/debug/dwarf (from $GOROOT)
	/private/tmp/delve20161005-6837-6240x5/delve-0.11.0-alpha/src/golang.org/x/debug/dwarf (from $GOPATH)
src/github.com/derekparker/delve/proc/proc_darwin.go:12:2: cannot find package "golang.org/x/debug/macho" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/debug/macho (from $GOROOT)
	/private/tmp/delve20161005-6837-6240x5/delve-0.11.0-alpha/src/golang.org/x/debug/macho (from $GOPATH)
src/github.com/derekparker/delve/proc/proc_darwin.go:21:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/sys/unix (from $GOROOT)
	/private/tmp/delve20161005-6837-6240x5/delve-0.11.0-alpha/src/golang.org/x/sys/unix (from $GOPATH)
src/github.com/derekparker/delve/config/config.go:10:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/gopkg.in/yaml.v2 (from $GOROOT)
	/private/tmp/delve20161005-6837-6240x5/delve-0.11.0-alpha/src/gopkg.in/yaml.v2 (from $GOPATH)
make: *** [build] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/go-delve/homebrew-delve/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:436:in `open'
	from /usr/local/Library/Homebrew/utils.rb:466:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:498:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:160:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'
```

**Comment by aarzilli** [comment]
you say you are using 1.6.2 but your paths say 1.5.1 are you sure you are using 1.6.2?

**Comment by LalatenduMohanty** [comment]
@aarzilli I have no idea why it is showing `/usr/local/Cellar/go/1.5.1/libexec` . Now I have went to go 1.7.1. But get the same exact error. 
```
$ go version
go version go1.7.1 darwin/amd64
```

**Comment by aarzilli** [comment]
considering you already have the certificate you could clone and build the repository manually, if this works then it's your install of homebrew that has a problem.

**Comment by LalatenduMohanty** [comment]
@aarzilli you are right, my home brew had some issue.  After fixing that it worked fine.
